# Generated by Django 5.2.1 on 2025-05-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
